version: '3'
services: 
  backend:
    build: 
      context: .
      dockerfile: ./Dockerfile
    tty: true 
    ports: 
      - 8000:8000
    volumes: 
      - ./backend:/root/src/backend
    restart: always

